// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/pbft_consensus.proto

package pbftconsensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the core information from an OpenFlow PacketIn message
type PacketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dpid          string                 `protobuf:"bytes,1,opt,name=dpid,proto3" json:"dpid,omitempty"`                          // Datapath ID as string
	InPort        uint32                 `protobuf:"varint,2,opt,name=in_port,json=inPort,proto3" json:"in_port,omitempty"`       // Input port number
	BufferId      uint32                 `protobuf:"varint,3,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"` // Buffer ID from the switch (important for PacketOut)
	TotalLen      uint32                 `protobuf:"varint,4,opt,name=total_len,json=totalLen,proto3" json:"total_len,omitempty"` // Total length of the packet
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                          // Raw packet data (bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketInfo) Reset() {
	*x = PacketInfo{}
	mi := &file_proto_pbft_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketInfo) ProtoMessage() {}

func (x *PacketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketInfo.ProtoReflect.Descriptor instead.
func (*PacketInfo) Descriptor() ([]byte, []int) {
	return file_proto_pbft_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *PacketInfo) GetDpid() string {
	if x != nil {
		return x.Dpid
	}
	return ""
}

func (x *PacketInfo) GetInPort() uint32 {
	if x != nil {
		return x.InPort
	}
	return 0
}

func (x *PacketInfo) GetBufferId() uint32 {
	if x != nil {
		return x.BufferId
	}
	return 0
}

func (x *PacketInfo) GetTotalLen() uint32 {
	if x != nil {
		return x.TotalLen
	}
	return 0
}

func (x *PacketInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Represents the action computed by Ryu (can be PacketOut or FlowMod)
// Using JSON string for flexibility initially. Could be more structured later.
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionJson    string                 `protobuf:"bytes,1,opt,name=action_json,json=actionJson,proto3" json:"action_json,omitempty"` // JSON representation of the action (e.g., {"type": "packet_out", "out_port": 5} or {"type": "flow_mod", ...})
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_pbft_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_pbft_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetActionJson() string {
	if x != nil {
		return x.ActionJson
	}
	return ""
}

// Request sent from Ryu Primary to PBFT Dealer
type ConsensusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PacketInfo     *PacketInfo            `protobuf:"bytes,1,opt,name=packet_info,json=packetInfo,proto3" json:"packet_info,omitempty"`
	ProposedAction *Action                `protobuf:"bytes,2,opt,name=proposed_action,json=proposedAction,proto3" json:"proposed_action,omitempty"` // The action computed by the Primary
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsensusRequest) Reset() {
	*x = ConsensusRequest{}
	mi := &file_proto_pbft_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusRequest) ProtoMessage() {}

func (x *ConsensusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusRequest.ProtoReflect.Descriptor instead.
func (*ConsensusRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *ConsensusRequest) GetPacketInfo() *PacketInfo {
	if x != nil {
		return x.PacketInfo
	}
	return nil
}

func (x *ConsensusRequest) GetProposedAction() *Action {
	if x != nil {
		return x.ProposedAction
	}
	return nil
}

// Response sent from PBFT Dealer to Ryu Primary
type ConsensusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinalAction      *Action                `protobuf:"bytes,1,opt,name=final_action,json=finalAction,proto3" json:"final_action,omitempty"`                 // The consensus-agreed action
	ConsensusReached bool                   `protobuf:"varint,2,opt,name=consensus_reached,json=consensusReached,proto3" json:"consensus_reached,omitempty"` // Indicates if consensus was successful
	StatusMessage    string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`           // e.g., "Consensus OK" or "Discrepancy Detected"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConsensusResponse) Reset() {
	*x = ConsensusResponse{}
	mi := &file_proto_pbft_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusResponse) ProtoMessage() {}

func (x *ConsensusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusResponse.ProtoReflect.Descriptor instead.
func (*ConsensusResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *ConsensusResponse) GetFinalAction() *Action {
	if x != nil {
		return x.FinalAction
	}
	return nil
}

func (x *ConsensusResponse) GetConsensusReached() bool {
	if x != nil {
		return x.ConsensusReached
	}
	return false
}

func (x *ConsensusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

// Request sent from PBFT Node to Ryu Replica
type CalculateActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketInfo    *PacketInfo            `protobuf:"bytes,1,opt,name=packet_info,json=packetInfo,proto3" json:"packet_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateActionRequest) Reset() {
	*x = CalculateActionRequest{}
	mi := &file_proto_pbft_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateActionRequest) ProtoMessage() {}

func (x *CalculateActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateActionRequest.ProtoReflect.Descriptor instead.
func (*CalculateActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateActionRequest) GetPacketInfo() *PacketInfo {
	if x != nil {
		return x.PacketInfo
	}
	return nil
}

// Response sent from Ryu Replica to PBFT Node
type CalculateActionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComputedAction *Action                `protobuf:"bytes,1,opt,name=computed_action,json=computedAction,proto3" json:"computed_action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateActionResponse) Reset() {
	*x = CalculateActionResponse{}
	mi := &file_proto_pbft_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateActionResponse) ProtoMessage() {}

func (x *CalculateActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateActionResponse.ProtoReflect.Descriptor instead.
func (*CalculateActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateActionResponse) GetComputedAction() *Action {
	if x != nil {
		return x.ComputedAction
	}
	return nil
}

var File_proto_pbft_consensus_proto protoreflect.FileDescriptor

const file_proto_pbft_consensus_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/pbft_consensus.proto\x12\rpbftconsensus\"\x87\x01\n" +
	"\n" +
	"PacketInfo\x12\x12\n" +
	"\x04dpid\x18\x01 \x01(\tR\x04dpid\x12\x17\n" +
	"\ain_port\x18\x02 \x01(\rR\x06inPort\x12\x1b\n" +
	"\tbuffer_id\x18\x03 \x01(\rR\bbufferId\x12\x1b\n" +
	"\ttotal_len\x18\x04 \x01(\rR\btotalLen\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\")\n" +
	"\x06Action\x12\x1f\n" +
	"\vaction_json\x18\x01 \x01(\tR\n" +
	"actionJson\"\x8e\x01\n" +
	"\x10ConsensusRequest\x12:\n" +
	"\vpacket_info\x18\x01 \x01(\v2\x19.pbftconsensus.PacketInfoR\n" +
	"packetInfo\x12>\n" +
	"\x0fproposed_action\x18\x02 \x01(\v2\x15.pbftconsensus.ActionR\x0eproposedAction\"\xa1\x01\n" +
	"\x11ConsensusResponse\x128\n" +
	"\ffinal_action\x18\x01 \x01(\v2\x15.pbftconsensus.ActionR\vfinalAction\x12+\n" +
	"\x11consensus_reached\x18\x02 \x01(\bR\x10consensusReached\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\"T\n" +
	"\x16CalculateActionRequest\x12:\n" +
	"\vpacket_info\x18\x01 \x01(\v2\x19.pbftconsensus.PacketInfoR\n" +
	"packetInfo\"Y\n" +
	"\x17CalculateActionResponse\x12>\n" +
	"\x0fcomputed_action\x18\x01 \x01(\v2\x15.pbftconsensus.ActionR\x0ecomputedAction2f\n" +
	"\rPBFTConsensus\x12U\n" +
	"\x10RequestConsensus\x12\x1f.pbftconsensus.ConsensusRequest\x1a .pbftconsensus.ConsensusResponse2s\n" +
	"\x0fRyuReplicaLogic\x12`\n" +
	"\x0fCalculateAction\x12%.pbftconsensus.CalculateActionRequest\x1a&.pbftconsensus.CalculateActionResponseB\x1eZ\x1cryu_pbft/proto;pbftconsensusb\x06proto3"

var (
	file_proto_pbft_consensus_proto_rawDescOnce sync.Once
	file_proto_pbft_consensus_proto_rawDescData []byte
)

func file_proto_pbft_consensus_proto_rawDescGZIP() []byte {
	file_proto_pbft_consensus_proto_rawDescOnce.Do(func() {
		file_proto_pbft_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pbft_consensus_proto_rawDesc), len(file_proto_pbft_consensus_proto_rawDesc)))
	})
	return file_proto_pbft_consensus_proto_rawDescData
}

var file_proto_pbft_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_pbft_consensus_proto_goTypes = []any{
	(*PacketInfo)(nil),              // 0: pbftconsensus.PacketInfo
	(*Action)(nil),                  // 1: pbftconsensus.Action
	(*ConsensusRequest)(nil),        // 2: pbftconsensus.ConsensusRequest
	(*ConsensusResponse)(nil),       // 3: pbftconsensus.ConsensusResponse
	(*CalculateActionRequest)(nil),  // 4: pbftconsensus.CalculateActionRequest
	(*CalculateActionResponse)(nil), // 5: pbftconsensus.CalculateActionResponse
}
var file_proto_pbft_consensus_proto_depIdxs = []int32{
	0, // 0: pbftconsensus.ConsensusRequest.packet_info:type_name -> pbftconsensus.PacketInfo
	1, // 1: pbftconsensus.ConsensusRequest.proposed_action:type_name -> pbftconsensus.Action
	1, // 2: pbftconsensus.ConsensusResponse.final_action:type_name -> pbftconsensus.Action
	0, // 3: pbftconsensus.CalculateActionRequest.packet_info:type_name -> pbftconsensus.PacketInfo
	1, // 4: pbftconsensus.CalculateActionResponse.computed_action:type_name -> pbftconsensus.Action
	2, // 5: pbftconsensus.PBFTConsensus.RequestConsensus:input_type -> pbftconsensus.ConsensusRequest
	4, // 6: pbftconsensus.RyuReplicaLogic.CalculateAction:input_type -> pbftconsensus.CalculateActionRequest
	3, // 7: pbftconsensus.PBFTConsensus.RequestConsensus:output_type -> pbftconsensus.ConsensusResponse
	5, // 8: pbftconsensus.RyuReplicaLogic.CalculateAction:output_type -> pbftconsensus.CalculateActionResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_pbft_consensus_proto_init() }
func file_proto_pbft_consensus_proto_init() {
	if File_proto_pbft_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pbft_consensus_proto_rawDesc), len(file_proto_pbft_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_pbft_consensus_proto_goTypes,
		DependencyIndexes: file_proto_pbft_consensus_proto_depIdxs,
		MessageInfos:      file_proto_pbft_consensus_proto_msgTypes,
	}.Build()
	File_proto_pbft_consensus_proto = out.File
	file_proto_pbft_consensus_proto_goTypes = nil
	file_proto_pbft_consensus_proto_depIdxs = nil
}
